"""add flashcards table

Revision ID: 8b32af67e990
Revises: adfee081ea73
Create Date: 2024-06-19 08:58:37.676748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b32af67e990'
down_revision: Union[str, None] = 'adfee081ea73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_topics_name', table_name='topics')
    op.drop_table('topics')
    op.drop_table('flashcards')
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    #     sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    #     sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    #     sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    #     # sa.Column('role', postgresql.ENUM('ADMIN', 'STUDENT', 'MENTOR', name='userrole'), autoincrement=False, nullable=True),
    #     sa.PrimaryKeyConstraint('id', name='users_pkey'),
    #     postgresql_ignore_search_path=False
    # )
    # op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    # op.create_table('flashcards',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    # sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='flashcards_topic_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='flashcards_pkey')
    # )
    # op.create_table('topics',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='topics_user_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='topics_pkey')
    # )
    # op.create_index('ix_topics_name', 'topics', ['name'], unique=False)
    # ### end Alembic commands ###
