"""init 2

Revision ID: 931b5ec4f961
Revises: 39e3d18c8232
Create Date: 2024-06-18 21:11:29.645660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931b5ec4f961'
down_revision: Union[str, None] = '39e3d18c8232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_human', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_human')
    # ### end Alembic commands ###
