version: "3.9"

services:
  web:
    image: repetit-be
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    command: gunicorn app.main:app -w 3 -b 0.0.0.0
      --worker-class uvicorn.workers.UvicornWorker
    ports:
      - "8000:8000"
